module.exports = {
    ENDPOINT_NAME : "endpointName",
    ENDPOINT_LIST : "endpointList",
    ENDPOINT_ID : "endpointId",
    PAYLOAD : "payload",
    SEND_PAYLOAD : "sendPayload",
    SERVICE_ID : "serviceId",
    ADVERTISE : "advertise",
    STRATEGY : "strategy",
    DISCOVER : "discover",
    NEW_MESSAGE : "new message",
    DISCONNECTING : "disconnecting",
    DISCONNECT : "disconnect",
    REQUEST_CONNECTION : "requestConnection",
    ACCEPT_CONNECTION : "acceptConnection",
    ON_ENDPOINT_FOUND : "onEndpointFound",
    ON_ENDPOINT_LOST : "onEndpointLost",
    ON_CONNECTION_RESULT : "onConnectionResult",
    ON_DISCONNECTED : "onDisconnected",
    ON_PAYLOAD_RECEIVED : "onPayloadReceived",
    ON_PAYLOAD_TRANSFER_UPDATE : "onPayloadTransferUpdate",
    STATE : "state",
    AUTH : "authentication",
    ON_CONNECTION_INITIATED : "onConnectionInitiated" ,
    SERVER_ADDRESS : "http://10.0.2.2:3000",
    SERVER_PORT : "3000",
    SOCKET_CONNECT : "socketConnect",
    STOP_DISCOVERY : "stopDiscovery",
    STOP_ADVERTISING : "stopAdvertising",
    PAYLOAD_RECEIVED : "payloadReceived"
};